export default{async fetch(request,env){const u=new URL(request.url);
if(u.pathname==="/api/health")return Response.json({ok:true,service:"NOUSA AI"});
if(u.pathname==="/api/status")return Response.json({worker:true,openaiKeyConfigured:!!env.OPENAI_API_KEY,hfTokenConfigured:!!env.HF_TOKEN,openaiModel:env.OPENAI_MODEL||"gpt-5.6-luna",imageProvider:"Hugging Face",videoProvider:"Hugging Face"});
if(u.pathname==="/api/chat"){if(request.method!=="POST")return Response.json({error:"Method not allowed"},{status:405});if(!env.OPENAI_API_KEY)return Response.json({error:"OPENAI_API_KEY is not configured. Chat needs an OpenAI API key/credits."},{status:503});let b;try{b=await request.json()}catch{return Response.json({error:"Invalid JSON."},{status:400})}
let allowed=["General","Maths","EVS","English","Hindi","Art & Craft"],s=allowed.includes(b.subject)?b.subject:"General",m=(Array.isArray(b.messages)?b.messages:[]).filter(x=>x&&(x.role==="user"||x.role==="assistant")&&typeof x.content==="string").slice(-20).map(x=>({role:x.role,content:x.content.slice(0,5000)}));if(!m.length)return Response.json({error:"Please enter a question."},{status:400});
let instructions=`You are NOUSA AI, a friendly school and creative assistant. Selected subject: ${s}. Maths: solve step-by-step. EVS: explain clearly with examples. English: grammar, writing, comprehension, vocabulary and literature. Hindi: answer in Hindi when appropriate; grammar, writing, meanings and literature. Art & Craft: materials and safe step-by-step project instructions. General: answer normally.`;
let r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":"Bearer "+env.OPENAI_API_KEY,"Content-Type":"application/json"},body:JSON.stringify({model:env.OPENAI_MODEL||"gpt-5.6-luna",instructions,input:m,max_output_tokens:1400,store:false})}),raw=await r.text();if(!r.ok){let z=raw;try{z=JSON.parse(raw)?.error?.message||raw}catch{}return Response.json({error:"OpenAI request failed.",status:r.status,details:String(z).slice(0,1200)},{status:502})}
let x;try{x=JSON.parse(raw)}catch{return Response.json({error:"Invalid OpenAI response."},{status:502})}let text=x.output_text||"";if(!text&&Array.isArray(x.output))for(const i of x.output||[])for(const c of i.content||[])if(typeof c.text==="string")text+=c.text;if(!text)return Response.json({error:"OpenAI returned no text.",details:JSON.stringify(x).slice(0,1200)},{status:502});return Response.json({text})}
if(u.pathname!=="/api/image"&&u.pathname!=="/api/video")return env.ASSETS.fetch(request);
if(request.method!=="POST")return Response.json({error:"Method not allowed"},{status:405});if(!env.HF_TOKEN)return Response.json({error:"HF_TOKEN is not configured. Add it in Cloudflare Variables & Secrets."},{status:503});
let b;try{b=await request.json()}catch{return Response.json({error:"Invalid JSON."},{status:400})}if(!b.prompt)return Response.json({error:"Please enter a prompt."},{status:400});
let model=u.pathname==="/api/image"?(env.HF_IMAGE_MODEL||"black-forest-labs/FLUX.1-schnell"):(env.HF_VIDEO_MODEL||"Wan-AI/Wan2.1-T2V-14B");
let r=await fetch("https://router.huggingface.co/hf-inference/models/"+model,{method:"POST",headers:{"Authorization":"Bearer "+env.HF_TOKEN,"Content-Type":"application/json"},body:JSON.stringify({inputs:String(b.prompt).slice(0,2000)})}),raw=await r.arrayBuffer(),ct=r.headers.get("content-type")||"";
if(!r.ok){let z=new TextDecoder().decode(raw);return Response.json({error:(u.pathname==="/api/image"?"Image":"Video")+" provider failed.",details:z.slice(0,1200)},{status:502})}
if(u.pathname==="/api/image"&&ct.startsWith("image/")){let a=new Uint8Array(raw),bin="";for(let i=0;i<a.length;i+=32768)bin+=String.fromCharCode(...a.subarray(i,i+32768));return Response.json({type:"image",url:"data:"+ct+";base64,"+btoa(bin)})}
if(u.pathname==="/api/video"&&ct.startsWith("video/")){let a=new Uint8Array(raw),bin="";for(let i=0;i<a.length;i+=32768)bin+=String.fromCharCode(...a.subarray(i,i+32768));return Response.json({type:"video",status:"completed",url:"data:"+ct+";base64,"+btoa(bin)})}
return Response.json({type:u.pathname==="/api/image"?"image":"video",status:"submitted",message:"The selected Hugging Face route did not return a finished media file. Try another supported model/provider by setting the corresponding model variable."})}}